services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/${GHCR_OWNER}/gameforum-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
      SERVER_PORT: "8080"
    depends_on:
      - db

  frontend:
    image: ghcr.io/${GHCR_OWNER}/gameforum-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
