create table achievements
(
    achievement_id          integer generated by default as identity
        primary key,
    achievement_name        varchar(255) not null
        unique,
    achievement_photo       oid,
    achievement_description text
);

alter table achievements
    owner to admin;

INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (2, 'First Battle', null, 'Created your first post on the battlefield');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (3, 'Veteran Commander', null, 'Commanded respect in 250 discussions');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (4, 'Master Strategist', null, 'Created a topic with 50+ replies');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (1, 'Town Founder', null, 'Created your first topic');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (5, 'Imperial Advisor', null, 'Became a moderator or admin');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (6, 'Explorer', null, 'Visited every category');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (7, 'Skirmisher', null, 'Engaged in 10 discussions with tactical precision');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (8, 'Line Infantry', null, 'A disciplined regular. 50 posts created');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (10, 'Warlord', null, 'A legendary figure of 1,000 battles');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (11, 'Master of the Battlefield', null, 'Dominated 5,000 engagements with unmatched skill');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (12, 'Unbreakable', null, '100 consecutive days active');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (13, 'Iron Will', null, '1 year of continuous service');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (14, 'Village Builder', null, '10 topics created');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (15, 'City Architect', null, '50 topics created');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (16, 'Capital Established', null, '200 topics created');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (17, 'Pillar of the Empire', null, 'Highly respected community member');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (18, 'Founder''s Seal', null, 'Early registration member');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (19, 'Imperial Favor', null, 'Granted by administrators');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (20, 'Legend of the Realm', null, 'Historic community figure');
INSERT INTO public.achievements (achievement_id, achievement_name, achievement_photo, achievement_description) VALUES (21, 'Hero of the Age', null, 'Wololoooo');
