create table category
(
    category_id          integer generated by default as identity
        primary key,
    category_description varchar(255),
    category_icon_name   varchar(255),
    category_name        varchar(255) not null
        unique,
    category_photo       oid
);

alter table category
    owner to admin;

INSERT INTO public.category (category_id, category_description, category_icon_name, category_name, category_photo) VALUES (1, 'Discuss anything related to Age of Empires III: Definitive Edition.', 'Scroll', 'General Discussion', 'https://cdn.magicpatterns.com/uploads/nqwtAMDkoHEAhDJ5qQpqJn/aoe-3.jpg');
INSERT INTO public.category (category_id, category_description, category_icon_name, category_name, category_photo) VALUES (2, 'Share build orders, combat tactics, and deck strategies.', 'Swords', 'Strategy & Tactics', 'https://cdn.magicpatterns.com/uploads/7bcwMP2sqDrc7nC6BGz1Yc/age-of-empires-35.jpg');
INSERT INTO public.category (category_id, category_description, category_icon_name, category_name, category_photo) VALUES (3, 'In-depth discussion about specific civilizations and their bonuses.', 'Flag', 'Civilizations', 'https://cdn.magicpatterns.com/uploads/7Heyziq6jW2xmPj6yEFs9N/ss_be0280e3c0013234dd6f55eedd021afcb4184594.1920x1080.jpg');
INSERT INTO public.category (category_id, category_description, category_icon_name, category_name, category_photo) VALUES (4, 'Find players, discuss ranked play, and organize tournaments.', 'Handshake', 'Multiplayer', 'https://cdn.magicpatterns.com/uploads/qNTG87Q4PGpGDmtU6Ae4oF/images.jpg');
INSERT INTO public.category (category_id, category_description, category_icon_name, category_name, category_photo) VALUES (5, 'Share your custom scenarios, mods, and map creations.', 'Wrench', 'Modding & Scenarios', 'https://cdn.magicpatterns.com/uploads/6VtQfUQujsm64DA7sH3hZT/181b573ea4b11e13a45344356c114e38035f584d.jpg');
